### ISSUE TITLE
Separate log files, code folders and git repositories for each service.

### ISSUE THREAD

**Issue by gtato** [ConPaaS-team/conpaas#100]
Every service (even if running inside the same application and sharing the same VM) should have its own log files and separate code folders and git repositories (or maybe just one git repository per application with different directories for each service?). At the moment I am pretty sure the folder/repository names are clashing.

**Comment by tcrivat** [comment]
Separate log files implemented in commit fe45dad9f2105a386d3db5b29b3c813d9d2e2e49. Separate code repositories added in 57f566cec25764f37a824792a643a8d97250cdd6. I kept only one git repository per application, with each service using a directory inside the same git repository, implemented in 65c2579ce1a95873ce30f0a8e61b35c3cc7fcc4d.
