### ISSUE TITLE
Test request: multi-cloud deployments

### ISSUE THREAD

**Issue by gpierre42** [ConPaaS-team/conpaas#28]
This is a request for testing the multi-cloud features of ConPaaS. The most obvious person to do this is @schevalier but it would be good if at least one other person would also take a look at this:

- Deploy ConPaaS with multiple clouds: either two different availability zones in AWS, or two separate OpenNebula installations, or one OpenNebula and one AWS zone. (warning for @schevalier : don't use Grid'5000 for the OpenNebula+AWS test! The Grid'5000 firewall will get in your way)

- Make sure you can deploy VMs in any of the selected clouds. 

- Make sure the VMs from different clouds can smoothly communicate with each other. In easy cases (e.g., two AWS zones) it may not be necessary to activate the IPOP virtual network. 

- Make sure VMs can communicate smoothly when the multi-cloud ConPaaS is configured to use the IPOP network.

**Comment by tcrivat** [comment]
Multi-cloud deployments are tested and work well. The old version of IPOP does not work anymore; the newer version should be integrated, I will add a new issue with this.
