### ISSUE TITLE
rc5 image for OpenNebula fails to get a certificate and key  

### ISSUE THREAD

**Issue by gtato** [ConPaaS-team/conpaas#67]
Hi guys,
I was trying the new image for the rc5 on OpenNebula on DAS4 and I get the following screen. 
![screenshot from 2014-09-22 14 20 55](https://cloud.githubusercontent.com/assets/5590184/4355958/6feab8bc-4253-11e4-87d0-d63aef759e89.png)

Actually I am not totally unfamiliar with this problem, I have encountered it also before but I don't remember how I overcame it. So maybe it is useful to document it here. 
Any idea of what the problem might be?

**Comment by tcrivat** [comment]
This was probably caused by a corrupted image. Not reproducible anymore.
